apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  type: {{ .Values.mysql.serviceType }}
  selector:
    app: mysql
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: TCP

---