apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate       # MySQL ke liye RollingUpdate avoid karo
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}:{{ .Values.mysql.tag }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "{{ .Values.mysql.resources.requests.memory }}"
              cpu: "{{ .Values.mysql.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.mysql.resources.limits.memory }}"
              cpu: "{{ .Values.mysql.resources.limits.cpu }}"
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: {{ .Values.mysql.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mysql.probes.readinessProbe.periodSeconds }}
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: {{ .Values.mysql.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mysql.probes.livenessProbe.periodSeconds }}
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---