apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    tier: application
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
        tier: application
    spec:
      initContainers:
        # MySQL ready hone ka wait karo
        - name: wait-for-mysql
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z mysql-service 3306; do
                echo "MySQL ka wait kar raha hoon..."
                sleep 3
              done
              echo "MySQL ready hai!"
      containers:
        - name: backend
          # ↓ Apni backend image yahan lagao
          image: {{ .Values.backend.image.repository }}/{{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: PORT
              value: "5000"
          resources:
            requests:
              memory: "{{ .Values.backend.resources.requests.memory }}"
              cpu: "{{ .Values.backend.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.backend.resources.limits.memory }}"
              cpu: "{{ .Values.backend.resources.limits.cpu }}"
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readinessProbe.path }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probes.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.livenessProbe.path }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.livenessProbe.periodSeconds }}

---